ALTER TABLE routes ADD COLUMN IF NOT EXISTS path geometry(LineString,4326) GENERATED ALWAYS AS (ST_SetSRID(ST_GeomFromGeoJSON(geojson::text),4326)) STORED;
CREATE INDEX IF NOT EXISTS ix_routes_path ON routes USING GIST(path);
-- Backend-only Supabase tables. RLS denies browser anon/authenticated roles access.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE refresh_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE weather_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE agriculture_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE historical_weather ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_deliveries ENABLE ROW LEVEL SECURITY;
